#!/bin/sh
# ── jj-setup.sh ────────────────────────────────────────────────────────────
# Run once after `jj git init --colocate` to wire jj to the SAME conventions
# the git hooks enforce. jj has no hook system, so we install aliases that run
# the shared validators (scripts/hooks/lib/rules.sh) before delegating to jj:
#
#   jj push   → validate branch + commit rules, then `jj git push`
#   jj check  → validate the current change without pushing
#
# Plus a draft commit-description template — the jj analogue of the git
# prepare-commit-msg hook. Config is written to the repo (.jj/repo/config.toml),
# mirroring how git-setup.sh writes local git config.
#
# Usage: sh scripts/jj-setup.sh
set -e

if ! command -v jj >/dev/null 2>&1; then
  echo "  [skip] jj not installed — nothing to do." >&2
  exit 0
fi
if ! jj root >/dev/null 2>&1; then
  echo "  [err] not a jj repo. Run: jj git init --colocate" >&2
  exit 1
fi

echo ""
echo "  CVOps — jj Setup"
echo "  ──────────────────────────────────────────────────────"

# ── identity ──────────────────────────────────────────────────────────────
jj config set --repo user.name  "Yehuda Briskman"
jj config set --repo user.email "yr0556772363@gmail.com"
echo "  [ok] identity"

# ── aliases: validation front-ends (jj has no hooks) ──────────────────────
# `bash -c '...' --` so trailing args jj appends become "$@" for the script.
jj config set --repo aliases.check \
  '["util", "exec", "--", "bash", "-c", "exec bash \"$JJ_WORKSPACE_ROOT/scripts/hooks/jj/validate.sh\" \"$@\"", "--"]'
jj config set --repo aliases.push \
  '["util", "exec", "--", "bash", "-c", "exec bash \"$JJ_WORKSPACE_ROOT/scripts/hooks/jj/pre-push.sh\" \"$@\"", "--"]'
echo "  [ok] aliases -> jj check, jj push"

# ── draft description template (≈ git prepare-commit-msg) ──────────────────
jj config set --repo templates.draft_commit_description '
concat(
  description,
  "\nJJ: ── commit convention ─────────────────────────────────\n",
  "JJ: <type>: <3-10 word imperative title>\n",
  "JJ: types: feat fix chore docs refactor style test lint\n",
  "JJ: then a blank line, then WHY (3-8 sentences).\n",
  "JJ: last line: Generated by [<Role>-Agent] [Claude-Bot] of [@<your-github-username>]\n",
  "JJ: ──────────────────────────────────────────────────────\n"
)
'
echo "  [ok] draft commit-description template"

echo "  ──────────────────────────────────────────────────────"
echo "  Done. Use jj like this:"
echo ""
echo "    jj describe -m \"feat: ...\"     # message is validated on push"
echo "    jj check                       # validate current change now"
echo "    jj bookmark set <Type>/<title> -r @"
echo "    jj push                        # validates, then jj git push"
echo ""
echo "  Conventions are identical to the git hooks (shared rule set)."
echo "  ──────────────────────────────────────────────────────"
echo ""
