"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-15 17:53:46.236853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('storage_backend', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('orgs',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_orgs_deleted_at'), 'orgs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_orgs_id'), 'orgs', ['id'], unique=False)
    op.create_table('type_schemas',
    sa.Column('type_key', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Text(), server_default='1', nullable=False),
    sa.Column('ui_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('type_key')
    )
    op.create_table('projects',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), server_default='detection', nullable=False),
    sa.Column('default_ontology_id', sa.Uuid(), nullable=True),
    sa.Column('default_ingest_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('collections',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_collections_project_name')
    )
    op.create_index(op.f('ix_collections_deleted_at'), 'collections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_project_id'), 'collections', ['project_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('blob_hash', sa.Text(), nullable=True),
    sa.Column('external_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blob_hash'], ['blobs.hash'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_deleted_at'), 'data_sources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_project_id'), 'data_sources', ['project_id'], unique=False)
    op.create_index('ix_data_sources_project_status', 'data_sources', ['project_id', 'status'], unique=False)
    op.create_index('uq_data_sources_project_blob', 'data_sources', ['project_id', 'blob_hash'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND blob_hash IS NOT NULL'))
    op.create_table('datasets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_datasets_project_name')
    )
    op.create_index(op.f('ix_datasets_deleted_at'), 'datasets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_table('memberships',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_memberships_org_user')
    )
    op.create_index(op.f('ix_memberships_deleted_at'), 'memberships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('ontologies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_ontologies_project_name')
    )
    op.create_index(op.f('ix_ontologies_deleted_at'), 'ontologies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ontologies_id'), 'ontologies', ['id'], unique=False)
    op.create_index(op.f('ix_ontologies_project_id'), 'ontologies', ['project_id'], unique=False)
    op.create_table('tags',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), server_default='#888888', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_tags_project_name')
    )
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_project_id'), 'tags', ['project_id'], unique=False)
    op.create_table('training_containers',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('icd_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('icd_schema_version', sa.Text(), server_default='1.0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_training_containers_project_name')
    )
    op.create_index(op.f('ix_training_containers_deleted_at'), 'training_containers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_training_containers_id'), 'training_containers', ['id'], unique=False)
    op.create_index(op.f('ix_training_containers_project_id'), 'training_containers', ['project_id'], unique=False)
    op.create_table('workflows',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Shape: {name, steps:[{id, type, config, inputs}], edges:[[from,to]]}'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_workflows_project_name')
    )
    op.create_index(op.f('ix_workflows_deleted_at'), 'workflows', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('parent_commit_id', sa.Uuid(), nullable=True),
    sa.Column('second_parent_commit_id', sa.Uuid(), nullable=True),
    sa.Column('ontology_id', sa.Uuid(), nullable=True),
    sa.Column('ontology_version', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.ForeignKeyConstraint(['parent_commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['second_parent_commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_dataset_id'), 'commits', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_commits_id'), 'commits', ['id'], unique=False)
    op.create_index(op.f('ix_commits_project_id'), 'commits', ['project_id'], unique=False)
    op.create_table('label_classes',
    sa.Column('ontology_id', sa.Uuid(), nullable=False),
    sa.Column('class_key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), server_default='#FF0000', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'class_key', name='uq_label_classes_ontology_key'),
    sa.UniqueConstraint('ontology_id', 'sort_order', name='uq_label_classes_ontology_order')
    )
    op.create_index(op.f('ix_label_classes_deleted_at'), 'label_classes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_label_classes_id'), 'label_classes', ['id'], unique=False)
    op.create_index(op.f('ix_label_classes_ontology_id'), 'label_classes', ['ontology_id'], unique=False)
    op.create_table('runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_version', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Text(), nullable=True),
    sa.Column('step_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('input_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logs_blob_hash', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['logs_blob_hash'], ['blobs.hash'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_deleted_at'), 'runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('samples',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('blob_hash', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('perceptual_hash', sa.Text(), nullable=True),
    sa.Column('thumbnail_hash', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Text(), server_default='unreviewed', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("review_status IN ('unreviewed','accepted','rejected')", name='ck_samples_review_status'),
    sa.ForeignKeyConstraint(['blob_hash'], ['blobs.hash'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_hash'], ['blobs.hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'blob_hash', name='uq_samples_project_blob')
    )
    op.create_index(op.f('ix_samples_deleted_at'), 'samples', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    op.create_index(op.f('ix_samples_project_id'), 'samples', ['project_id'], unique=False)
    op.create_index('ix_samples_project_review_status', 'samples', ['project_id', 'review_status'], unique=False)
    op.create_index(op.f('ix_samples_source_id'), 'samples', ['source_id'], unique=False)
    op.create_table('annotation_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('ontology_id', sa.Uuid(), nullable=False),
    sa.Column('ontology_version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['annotation_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_revisions_id'), 'annotation_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_annotation_revisions_project_id'), 'annotation_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_annotation_revisions_sample_id'), 'annotation_revisions', ['sample_id'], unique=False)
    op.create_index('ix_annotation_revisions_sample_revision', 'annotation_revisions', ['sample_id', 'revision_no'], unique=False)
    op.create_table('collection_samples',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'sample_id')
    )
    op.create_index('ix_collection_samples_sample_id', 'collection_samples', ['sample_id'], unique=False)
    op.create_table('labeling_jobs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Text(), nullable=False),
    sa.Column('cvat_project_id', sa.Integer(), nullable=True),
    sa.Column('cvat_task_id', sa.Integer(), nullable=False),
    sa.Column('cvat_job_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Text(), server_default='pushed', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('annotation_revision_ids_in', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotation_revision_ids_out', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labeling_jobs_deleted_at'), 'labeling_jobs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_labeling_jobs_id'), 'labeling_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_labeling_jobs_project_id'), 'labeling_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_labeling_jobs_run_id'), 'labeling_jobs', ['run_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('blob_hash', sa.Text(), nullable=False),
    sa.Column('trained_on_commit_id', sa.Uuid(), nullable=False),
    sa.Column('training_container_id', sa.Uuid(), nullable=True),
    sa.Column('base_model', sa.Text(), nullable=True),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code_version', sa.Text(), nullable=True),
    sa.Column('env_hash', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('mlflow_run_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blob_hash'], ['blobs.hash'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['trained_on_commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['training_container_id'], ['training_containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_deleted_at'), 'model_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_model_versions_project_id'), 'model_versions', ['project_id'], unique=False)
    op.create_table('refs',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('ref_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_commit_id', sa.Uuid(), nullable=False),
    sa.Column('is_mutable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['target_commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'ref_type', 'name', name='uq_refs_dataset_type_name')
    )
    op.create_index(op.f('ix_refs_dataset_id'), 'refs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_refs_deleted_at'), 'refs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_refs_id'), 'refs', ['id'], unique=False)
    op.create_table('sample_tags',
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'tag_id')
    )
    op.create_index('ix_sample_tags_tag_id', 'sample_tags', ['tag_id'], unique=False)
    op.create_table('commit_samples',
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_revision_id', sa.Uuid(), nullable=True),
    sa.Column('split', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_revision_id'], ['annotation_revisions.id'], ),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('commit_id', 'sample_id')
    )
    op.create_index('ix_commit_samples_commit_id', 'commit_samples', ['commit_id'], unique=False)
    op.create_table('project_dataset_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('pinned_commit_id', sa.Uuid(), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(pinned_commit_id IS NOT NULL AND ref_id IS NULL) OR (pinned_commit_id IS NULL AND ref_id IS NOT NULL)', name='ck_project_dataset_links_one_target'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['pinned_commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['ref_id'], ['refs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'dataset_id', name='uq_project_dataset_links_project_dataset')
    )
    op.create_index(op.f('ix_project_dataset_links_dataset_id'), 'project_dataset_links', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_project_dataset_links_deleted_at'), 'project_dataset_links', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_dataset_links_id'), 'project_dataset_links', ['id'], unique=False)
    op.create_index(op.f('ix_project_dataset_links_project_id'), 'project_dataset_links', ['project_id'], unique=False)
    # ### end Alembic commands ###

    # Deferred circular FKs: projects references ontologies/workflows, which in
    # turn reference projects, so these are added after all tables exist.
    op.create_foreign_key(
        'fk_projects_default_ontology', 'projects', 'ontologies',
        ['default_ontology_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_projects_default_ingest_workflow', 'projects', 'workflows',
        ['default_ingest_workflow_id'], ['id'],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_default_ingest_workflow', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_default_ontology', 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_project_dataset_links_project_id'), table_name='project_dataset_links')
    op.drop_index(op.f('ix_project_dataset_links_id'), table_name='project_dataset_links')
    op.drop_index(op.f('ix_project_dataset_links_deleted_at'), table_name='project_dataset_links')
    op.drop_index(op.f('ix_project_dataset_links_dataset_id'), table_name='project_dataset_links')
    op.drop_table('project_dataset_links')
    op.drop_index('ix_commit_samples_commit_id', table_name='commit_samples')
    op.drop_table('commit_samples')
    op.drop_index('ix_sample_tags_tag_id', table_name='sample_tags')
    op.drop_table('sample_tags')
    op.drop_index(op.f('ix_refs_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_deleted_at'), table_name='refs')
    op.drop_index(op.f('ix_refs_dataset_id'), table_name='refs')
    op.drop_table('refs')
    op.drop_index(op.f('ix_model_versions_project_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_deleted_at'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_labeling_jobs_run_id'), table_name='labeling_jobs')
    op.drop_index(op.f('ix_labeling_jobs_project_id'), table_name='labeling_jobs')
    op.drop_index(op.f('ix_labeling_jobs_id'), table_name='labeling_jobs')
    op.drop_index(op.f('ix_labeling_jobs_deleted_at'), table_name='labeling_jobs')
    op.drop_table('labeling_jobs')
    op.drop_index('ix_collection_samples_sample_id', table_name='collection_samples')
    op.drop_table('collection_samples')
    op.drop_index('ix_annotation_revisions_sample_revision', table_name='annotation_revisions')
    op.drop_index(op.f('ix_annotation_revisions_sample_id'), table_name='annotation_revisions')
    op.drop_index(op.f('ix_annotation_revisions_project_id'), table_name='annotation_revisions')
    op.drop_index(op.f('ix_annotation_revisions_id'), table_name='annotation_revisions')
    op.drop_table('annotation_revisions')
    op.drop_index(op.f('ix_samples_source_id'), table_name='samples')
    op.drop_index('ix_samples_project_review_status', table_name='samples')
    op.drop_index(op.f('ix_samples_project_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_deleted_at'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_deleted_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_label_classes_ontology_id'), table_name='label_classes')
    op.drop_index(op.f('ix_label_classes_id'), table_name='label_classes')
    op.drop_index(op.f('ix_label_classes_deleted_at'), table_name='label_classes')
    op.drop_table('label_classes')
    op.drop_index(op.f('ix_commits_project_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_dataset_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_deleted_at'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_training_containers_project_id'), table_name='training_containers')
    op.drop_index(op.f('ix_training_containers_id'), table_name='training_containers')
    op.drop_index(op.f('ix_training_containers_deleted_at'), table_name='training_containers')
    op.drop_table('training_containers')
    op.drop_index(op.f('ix_tags_project_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_ontologies_project_id'), table_name='ontologies')
    op.drop_index(op.f('ix_ontologies_id'), table_name='ontologies')
    op.drop_index(op.f('ix_ontologies_deleted_at'), table_name='ontologies')
    op.drop_table('ontologies')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_deleted_at'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_deleted_at'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('uq_data_sources_project_blob', table_name='data_sources', postgresql_where=sa.text('deleted_at IS NULL AND blob_hash IS NOT NULL'))
    op.drop_index('ix_data_sources_project_status', table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_project_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_deleted_at'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_collections_project_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_deleted_at'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('type_schemas')
    op.drop_index(op.f('ix_orgs_id'), table_name='orgs')
    op.drop_index(op.f('ix_orgs_deleted_at'), table_name='orgs')
    op.drop_table('orgs')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_table('blobs')
    # ### end Alembic commands ###
